#!/bin/bash
#
# GRID-BUILD

##	need to set paths
##  need to install dependencies
##		- can be run from host to config clients with software
##  loop over input commands? maybe with gnu parallel?
##  download source and edit build files to fix bugs
##	script & launch installer w config files
##	install/download necessary software on nodes


function grid-build(){
	
}